Repository Visual-Testing-for-Android-Apps/backend, pull requests merged in 2021-10, with the labels that each got.

#76 update emails to read better
  server/jobHandler/src/jobProcessingEmail.ts
  server/reportGenerator/src/sendEmail.ts
Labels: JavaScript, CloudFormation

#77 Update/lucille/report gen
  README.md
  server/reportGenerator/src/reportGen.ts
Labels: TypeScript

#69 periodicFileRemoval
  server/periodicFileRemoval/README.md
  server/periodicFileRemoval/app.py
  server/template.yml
Labels: Python, CloudFormation
