Repository Visual-Testing-for-Android-Apps/backend, pull requests merged in 2021-09, with the labels that each got.

#21 bugfix-uploadHandler
  .gitignore
  README.md
  file_upload_handler/uploads/TestEndpoint.http
  server/owlEye/app/app.py
  server/owlEye/app/index.py
  server/seenomaly/lambda/multiEventHandler.py
  server/template.yml
  server/uploadHandler/src/createNewJob.ts
  server/uploadHandler/src/index.ts
  server/uploadHandler/src/service/S3Client.ts
  server/uploadHandler/src/service/dynamodbService.ts
  server/uploadHandler/src/service/jobModel.ts
  server/uploadHandler/src/service/sqsClient.ts
Labels: Python, TypeScript, CloudFormation, README

#26 Feature/peter/is job complete
  .gitignore
  README.md
  package-lock.json
  package.json
  server/isJobComplete/.eslintignore
  server/isJobComplete/.eslintrc.js
  server/isJobComplete/.prettierignore
  server/isJobComplete/Makefile
  server/isJobComplete/jest.config.js
  server/isJobComplete/package-lock.json
  server/isJobComplete/package.json
  server/isJobComplete/src/index.test.ts
  server/isJobComplete/src/index.ts
  server/isJobComplete/src/service/dynamodbClient.ts
  server/isJobComplete/src/service/dynamodbService.ts
  server/isJobComplete/tsconfig.json
  server/sendEmail/package-lock.json
  server/sendEmail/package.json
  server/sendEmail/src/index.ts
  server/template.yml
  server/tsconfig.json
  server/uploadHandler/.eslintrc.js
  server/uploadHandler/jest.config.js
Labels: TypeScript, CloudFormation

#32 Email verification in uploadHandler
  README.md
  file_upload_handler/uploads/TestEndpoint.http
  package-lock.json
  package.json
  server/owlEye/app/app.py
  server/owlEye/app/index.py
  server/seenomaly/lambda/multiEventHandler.py
  server/template.yml
  server/uploadHandler/package-lock.json
  server/uploadHandler/package.json
  server/uploadHandler/src/createNewJob.ts
  server/uploadHandler/src/index.test.ts
  server/uploadHandler/src/index.ts
  server/uploadHandler/src/service/S3Client.ts
  server/uploadHandler/src/service/dynamodbService.ts
  server/uploadHandler/src/service/jobModel.ts
  server/uploadHandler/src/service/sesService.ts
  server/uploadHandler/src/service/sqsClient.ts
Labels: Python, TypeScript, CloudFormation
